{{- if .Values.vpa.admissionController.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.name" . }}
  labels:
    {{- include "vertical-pod-autoscaler.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-controller
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "vertical-pod-autoscaler.admissionController.name" . }}
webhooks:
- name: vpa.k8s.io
  admissionReviewVersions:
  - v1
  - v1beta1
  failurePolicy: Ignore
  sideEffects: None
  clientConfig:
    service:
      name: {{ include "vertical-pod-autoscaler.admissionController.name" . }}
      namespace: {{ .Release.Namespace }}
      path: "/"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["autoscaling.k8s.io"]
    apiVersions: ["*"]
    resources: ["verticalpodautoscalers"]
{{- end }}