global:
  # -- Cloud specific bindings (options: aws, gcp)
  cloud: ""

job:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1

  image:
    repository: "busybox"
    tag: "latest"
    # -- Whether the repository is public
    isRepositoryPublic: true

  config:
    command: []
    #  - "/bin/sh"
    args: []
    #  - "-c"
    #  - "echo 'Environment $(hello_env)! Secret $(username).'"
    env: {}
    #  hello_env: "world"
    secrets: {}
    #  username: "password"

dockerconfigjson:
  # -- Name of the secret to use for the private repository
  name: "snowplow-cron-job-dockerhub"
  # -- Username for the private repository
  username: ""
  # -- Password for the private repository
  password: ""
  # -- Repository server URL
  server: "https://index.docker.io/v1/"
  # -- Email address for user of the private repository
  email: ""

cloudserviceaccount:
  # -- Whether to create a service-account
  deploy: false
  # -- Name of the service-account to create
  name: "snowplow-cron-job-service-account"
  aws:
    # -- IAM Role ARN to bind to the k8s service account
    roleARN: ""
  gcp:
    # -- Service Account email to bind to the k8s service account
    serviceAccount: ""
