apiVersion: cert-manager.io/v1
kind: {{if eq .Values.issuerType "namespace"}}Issuer{{else if eq .Values.issuerType "cluster"}}ClusterIssuer{{end}}
metadata:
  name: {{ include "app.fullname" . }}
spec:
  {{- if .Values.acme.enabled}}
  acme:
    {{- if eq (include "app.fullname" .) "letsencrypt" }}
    email: {{ .Values.acme.email }}
    {{- else if contains "external" (include "app.fullname" .) }}
    externalAccountBinding:
      keyID: {{ .Values.acme.EABKeyId }}
      keySecretRef:
        name: {{ include "app.fullname" . }}-eabsecret
        key: secret
      keyAlgorithm: HS256
    {{- end}}
    {{- if .Values.acme.accountPrivateKeyData}}
    disableAccountKeyGeneration: true
    {{- end }}
    server: {{ include "acme.server" . }}
    privateKeySecretRef:
        name: {{ include "app.fullname" . }}-account-key
    solvers:
    {{- if eq .Values.acme.solver "http01"}}
    - http01:
        ingress:
          class: {{ $.Values.acme.httpSolverIngressClass }}
    {{- end}}
  {{- end}}
