{{ if .Values.acme.accountPrivateKeyData }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "app.fullname" . }}-account-key
    namespace: {{ if eq .Values.issuerType "cluster" }}cert-manager{{else}}{{ .Release.Namespace }}{{end}}
type: Opaque
data:
    tls.key: {{ .Values.acme.accountPrivateKeyData | b64enc | quote }}
{{ end }}
