{{- if .Values.mockTarget.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "avalanche.fullname" . }}-mock-target
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snowplow.labels" . | nindent 4 }}
    app.kubernetes.io/component: mock-target
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mockTarget.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "avalanche.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mock-target
{{- end }}
