apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ include "githubActionsRunners.componentname" (list . "horizontalrunnerautoscaler") }}
  labels:
    helm.sh/chart: {{ include "githubActionsRunners.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/component: HorizontalRunnerAutoscaler
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    name: {{ $.Values.runnerDeployment.name }}
  scaleDownDelaySecondsAfterScaleOut: {{ $.Values.runnerDeployment.scaleDownDelaySecondsAfterScaleOut }}
  minReplicas: {{ $.Values.runnerDeployment.minimumReplicaCount }}
  maxReplicas: {{ $.Values.runnerDeployment.maximumReplicaCount }}
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"
