apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ $.Values.runnerDeployment.runnerDeploymentName }}
  {{- if not eq .Values.runnerDeployment.runnerNamespace "" -}}
  namespace: {{ $.Values.runnerDeployment.runnerNamespace }}
  {{-end-}}
  labels:
    helm.sh/chart: {{ include "github_actions_runners.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: RunnerDeployment
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  replicas: 0
  template:
    spec:
      {{- if eq .Values.runnerDeployment.deploymentType "repository" }}
      repository: {{ $.Values.runnerDeployment.repositoryName  }}
      {{- end}}
      {{- if eq .Values.runnerDeployment.deploymentType "organization" }}
      organization: {{ $.Values.runnerDeployment.organizationName  }}
      {{- end}}
      {{- if eq .Values.runnerDeployment.deploymentType "enterprise" }}
      enterprise: {{ $.Values.runnerDeployment.enterpriseName  }}
      {{- end}}
      image: {{ $.Values.runnerDeployment.image.runnerImage }}
      imagePullPolicy: {{ $.Values.runnerDeployment.image.pullPolicy }}
      {{- if not .Values.runnerDeployment.isRepositoryPublic }}
      imagePullSecrets:
      - name: {{ .Values.secrets.docker.name }}
      {{- end}}
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"