{{- if not .Values.runnerDeployment.image.isRepositoryPublic -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.runnerDeployment.runnerNamespace }}
  name: {{ .Values.secrets.docker.name }}
type: kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{ tpl (.Files.Get "configs/secret_docker.json") . | b64enc }}
{{- end -}}