{{- define "common.serviceaccount" -}}
{{- $global := .Values.global -}}
{{- $release := .Release -}}
{{- range .Values.services }}
{{- if and .cloudserviceaccount .cloudserviceaccount.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ $release.Namespace }}
  name: {{ .cloudserviceaccount.name }}
  annotations:
  {{- if and $global (eq $global.cloud "gcp") .cloudserviceaccount.gcp .cloudserviceaccount.gcp.serviceAccount }}
    iam.gke.io/gcp-service-account: {{ .cloudserviceaccount.gcp.serviceAccount }}
  {{- else if and $global (eq $global.cloud "aws") .cloudserviceaccount.aws .cloudserviceaccount.aws.roleARN }}
    eks.amazonaws.com/role-arn: {{ .cloudserviceaccount.aws.roleARN }}
  {{- else if and $global (eq $global.cloud "azure") .cloudserviceaccount.azure .cloudserviceaccount.azure.managedIdentityId }}
    azure.workload.identity/client-id: {{ .cloudserviceaccount.azure.managedIdentityId }}
  {{- end }}
{{- if .cloudserviceaccount.secrets }}
secrets:
{{- range $v := .cloudserviceaccount.secrets }}
-  name: {{ $v }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
