{{- define "common.vpa" -}}
{{- $global := .Values.global -}}
{{- range .Values.services }}
{{- if .vpa.enabled }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .name }}
  labels:
    {{- with $global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: {{ .deployment.kind }}
    name: {{ .name }}
  {{- if .vpa.spec }}
  {{- toYaml .vpa.spec | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
