{{- define "common.certificate" -}}
{{- $global := .Values.global -}}
{{- range .Values.services }}
{{- range .service.ingress }}
{{- if and (.certificateCreate | default true) (not .tlsSecretName) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ required "A valid hostname is required!" .hostname | replace "." "-" }}
  labels:
    {{- with $global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  secretName: {{ .hostname }}-tls
  issuerRef:
    name: "{{ .certificateIssuerName | default "letsencrypt" }}"
    kind: "{{ .certificateIssuerKind | default "ClusterIssuer" }}"
  commonName: "{{ required "A valid hostname is required!" .hostname }}"
  dnsNames:
  - "{{ required "A valid hostname is required!" .hostname }}"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
