{{- define "common.clusterrolebinding" -}}
{{- $global := .Values.global -}}
{{- $release := .Release -}}
{{- range .Values.services }}
{{- if .clusterrole.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}
  labels:
    {{- with $global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .name }}
subjects:
{{- if .cloudserviceaccount.deploy }}
- apiGroup:
  kind: ServiceAccount
  name: {{ .cloudserviceaccount.name }}
  namespace: {{ $release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
