apiVersion: v2
name: priority-class
description: A Helm Chart to setup priority classes for all tiers
version: 0.1.0
icon: https://raw.githubusercontent.com/snowplow-devops/helm-charts/master/docs/logo/snowplow.png
home: https://github.com/snowplow-devops/helm-charts
sources:
  - https://github.com/snowplow-devops/helm-charts
maintainers:
  - name: ianarsenault
    url: https://github.com/ianarsenault
    email: ianarsenault@users.noreply.github.com
keywords:
  - priority-class
  - priority-classes
