apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{ include "snowplow.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.fullname" . }}
        {{ include "snowplow.labels" $ | nindent 8 }}
    spec:
      priorityClassName: {{ include "app.fullname" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: "{{ include "app.fullname" . }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
