apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.fullname" . }}
    spec:
      priorityClassName: {{ include "app.fullname" . }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: "{{ include "app.fullname" . }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
