{{- range .Values.policies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "network-policy.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- range $k, $v := .podSelector }}
      {{ $k }}: {{ $v }}
      {{- end }}

  policyTypes:
    {{- include "network-policy.policyTypes" . | nindent 4 }}
  
  {{- if .ingress }}
    {{- include "network-policy.ingress" . | indent 2 }}
  {{- end }}

  {{- if .egress }}
    {{- include "network-policy.egress" . | indent 2 }}
  {{- end }}

---
{{- end }}
