# -- Whether to create a service-account
deploy: false
# -- Name of the service-account to create
name: "my-service-account"
aws:
  # -- IAM Role ARN to bind to the k8s service account
  roleARN: ""
gcp:
  # -- Service Account email to bind to the k8s service account
  serviceAccount: ""
azure:
  # -- Workload managed identity id to bind to the k8s service account
  managedIdentityId: ""
# -- List of secrets allowed to be used by pods running using this ServiceAccount
secrets: []
# - ssl-certificates
