global:
  # -- Cloud specific bindings (options: aws, gcp, azure. Only used for dns01 type)
  cloud: ""

# -- The type of issuer to create (options: cluster, namespace)
issuerType: "cluster"

acme:
  # -- Whether to enable the ACME protocol
  enabled: true
  # -- The ACME server to use (options: letsencrypt, letsencrypt-staging, external-zerossl)
  environment: letsencrypt-staging
  # -- The email address to use for registration
  email: "firstname.lastname@example.com"
  # -- A private key to use for registration (if not provided, one will be generated)
  accountPrivateKeyData: ""
  # -- External Account Binding (EAB) Key ID, required for ACME registration with providers like ZeroSSL.
  EABKeyId: ""
  # -- External Account Binding (EAB) HMAC Key, used to cryptographically sign requests during ACME registration.
  EABHmacKey: ""
  # -- The type of challenge to use (options: http01, dns01)
  solver: "http01"
  # -- The name of the ingress class to setup the HTTP-01 challenge solver on
  httpSolverIngressClass: "traefik"

  dnsSolver:
    # -- The type of DNS solver to use (options: route53)
    type: ""   
