apiVersion: v2
name: network-policy
description: A Helm chart to deploy a Kubernetes NetworkPolicy
version: 0.1.0
icon: https://raw.githubusercontent.com/snowplow-devops/helm-charts/master/docs/logo/snowplow.png
home: https://github.com/snowplow-devops/helm-charts
sources:
  - https://github.com/snowplow-devops/helm-charts
maintainers:
  - name: jamesarems
    url: https://github.com/jamesarems
    email: jamesarems@users.noreply.github.com
keywords:
  - network-policy
  - network-policies
