apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: "{{ .Values.concurrencyPolicy }}"
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "app.fullname" . }}
          annotations:
            {{- if .Values.configMaps }}
            {{- range $v := .Values.configMaps }}
            {{- range $f := $v.files }}
            {{- if $f.contentsB64 }}
            checksum/{{ $v.name }}-{{ $f.key }}: "{{ $f.contentsB64 | sha256sum }}"
            {{- else }}
            checksum/{{ $v.name }}-{{ $f.key }}: "{{ ($.Files.Get $f.contentsFile) | b64enc | sha256sum }}"
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
        spec:
          {{- if .Values.cloudserviceaccount.deploy }}
          serviceAccountName: {{ .Values.cloudserviceaccount.name }}
          {{- end }}
          automountServiceAccountToken: true

          {{- if not .Values.image.isRepositoryPublic }}
          imagePullSecrets:
          - name: {{ .Values.dockerconfigjson.name }}
          {{- end }}

          restartPolicy: "{{ .Values.restartPolicy }}"

          {{- if .Values.configMaps }}
          volumes:
          {{- range $v := .Values.configMaps }}
          - configMap:
              name: {{ $v.name }}
              optional: false
            name: {{ $v.name }}
          {{- end }}
          {{- end }}

          containers:
          - name: "{{ include "app.fullname" . }}"
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}

            {{- if .Values.config.command  }}
            command:
            {{- range $v := .Values.config.command }}
            - "{{ $v }}"
            {{- end }}
            {{- end }}

            {{- if .Values.config.args  }}
            args:
            {{- range $v := .Values.config.args }}
            - "{{ $v }}"
            {{- end }}
            {{- end }}

            {{- if .Values.config.env  }}
            env:
            {{- range $k, $v := .Values.config.env }}
            - name: "{{ $k }}"
              value: "{{ $v }}"
            {{- end }}
            {{- end }}
            
            {{- if .Values.config.secrets  }}
            envFrom:
            - secretRef:
                name: {{ include "app.secret.fullname" . }}
            {{- end }}

            {{- if .Values.configMaps }}
            volumeMounts:
            {{- range $v := .Values.configMaps }}
            - mountPath: "{{ $v.mountPath }}"
              {{- if $v.mountPropagation }}
              mountPropagation: {{ $v.mountPropagation }}
              {{- else }}
              mountPropagation: None
              {{- end }}
              name: {{ $v.name }}
            {{- end }}
            {{- end }}
