{{- if and .Values.cloudserviceaccount.deploy .Values.customRole.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "snowplow.labels" $ | nindent 4 }}
rules:
- apiGroups:
  {{- range $v := .Values.customRole.apiGroups }}
  - {{ $v | quote }}
  {{- end }}
  resources:
  {{- range $v := .Values.customRole.resources }}
  - {{ $v | quote }}
  {{- end }}
  verbs:
  {{- range $v := .Values.customRole.verbs }}
  - {{ $v | quote }}
  {{- end }}
{{- end }}
