{{- if and .Values.cloudserviceaccount.deploy .Values.customRole.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "snowplow.labels" $ | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.cloudserviceaccount.name }}
roleRef:
  kind: Role
  name: {{ include "app.fullname" . }}
  apiGroup: rbac.authorization.k8s.io 
{{- end }}
