{{- if .Values.job.config.secrets  }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "job.app.secret.name" . }}
type: Opaque
data:
  {{- range $k, $v := .Values.job.config.secrets }}
  {{ $k }}: "{{ $v | b64enc }}"
  {{- end }}
{{- end }}
