apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transformer.app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "transformer.app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "transformer.app.name" . }}
        environment: "TODO:environment"
        supplier: "TODO:snowplow"
      annotations:
        checksum/config: "{{ include "transformer.service.config.checksum" . }}"
        {{- if ne .Values.service.config.hoconBase64 "" }}
        checksum/config.hocon: "{{ .Values.service.config.hoconBase64 | sha256sum}}"
        {{- end }}
        {{- if ne .Values.service.config.igluResolverBase64 "" }}
        checksum/config.igluResolver: "{{ .Values.service.config.igluResolverBase64 | sha256sum}}"
        {{- end }}
    spec:
      {{- if .Values.cloudserviceaccount.deploy }}
      serviceAccountName: {{ .Values.cloudserviceaccount.name }}
      {{- end }}
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: {{ .Values.service.terminationGracePeriodSeconds }}

      {{- if not .Values.service.image.isRepositoryPublic }}
      imagePullSecrets:
      - name: {{ .Values.dockerconfigjson.name }}
      {{- end }}

      volumes:
      {{- if ne .Values.service.config.hoconBase64 "" }}
      - configMap:
          name: {{ include "transformer.app.config.name" . }}
          optional: false
        name: {{ include "transformer.app.config.name" . }}-volume
      {{- end }}

      containers:
      - name: {{ include "transformer.app.name" . }}
        image: {{ .Values.service.image.repository}}:{{ .Values.service.image.tag}}
        imagePullPolicy: {{ default "IfNotPresent" .Values.service.image.pullPolicy }}

        args:
        - "-Dconfig.override_with_env_vars=true"
        {{- if ne .Values.service.config.igluResolverBase64 "" }}
        - "--iglu-config"
        - "/etc/config/config.igluResolver"
        {{- end }}
        {{- if ne .Values.service.config.hoconBase64 "" }}
        - "--config"
        - "/etc/config/config.hocon"
        {{- end }}

        ports:
        - containerPort: {{ .Values.service.port }}
          protocol: TCP

        env:
        {{- if not (empty .Values.service.config.javaOpts) }}
        - name : "JAVA_OPTS"
          value: "{{ .Values.service.config.javaOpts }}"
        {{- end }}

        envFrom:
        - secretRef:
            name: {{ include "transformer.app.secret.name" . }}

        readinessProbe:
          httpGet:
            path: /api/meta/health
            port: {{ .Values.service.port }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.service.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.service.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.service.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.service.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.service.readinessProbe.successThreshold }}

        resources:
          {{- toYaml .Values.service.resources | nindent 10 }}

        volumeMounts:
        {{- if ne .Values.service.config.hoconBase64 "" }}
        - mountPath: /etc/config
          mountPropagation: None
          name: {{ include "transformer.app.config.name" . }}-volume
        {{- end }}
