apiVersion: v1
kind: Service
metadata:
  name: {{ include "transformer.app.name" . }}
  {{- if eq .Values.global.cloud "gcp" }}
  annotations:
    cloud.google.com/app-protocols:  '{"http-port": "HTTP"}'
    cloud.google.com/neg: '{"exposed_ports": {"{{ .Values.service.port }}":{"name": "{{ include "transformer.service.gcp.networkEndpointGroupName" . }}"}}}'
  {{- end }}
spec:
  type: NodePort
  selector:
    app: {{ include "transformer.app.name" . }}
  ports:
  - name: http-port
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
