{{- range .Values.service.ingress }}
{{- if .certificateCreate  | default "true" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ required "A valid hostname is required!" .hostname }}
spec:
  secretName: {{ .hostname }}-tls
  issuerRef:
    name: "{{ .certificateIssuerName | default "letsencrypt" }}"
    kind: "{{ .certificateIssuerKind | default "ClusterIssuer" }}"
  commonName: "{{ required "A valid hostname is required!" .hostname }}"
  dnsNames:
  - "{{ required "A valid hostname is required!" .hostname }}"
{{- end }}
{{- end }}
