apiVersion: apps/v1
kind: {{ .Values.deployment.kind }}
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "snowplow.labels" $ | nindent 4 }}
spec:
  {{- if .Values.deployment.scaleToZero }}
  replicas: 0
  {{- else if not .Values.hpa.deploy }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    {{- if eq .Values.deployment.strategy.type "RollingUpdate"}}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "snowplow.labels" $ | nindent 8 }}
        {{- if .Values.deployment.podLabels }}
        {{- toYaml .Values.deployment.podLabels | nindent 8 }}
        {{- end }}
        app: {{ include "app.fullname" . }}
        {{- if eq .Values.global.cloud "azure" }}
        azure.workload.identity/use: "true"
        {{- end }}
      annotations:
        checksum/values: "{{ toJson .Values | sha256sum }}"
    spec:
      {{- if .Values.cloudserviceaccount.deploy }}
      serviceAccount: {{ .Values.cloudserviceaccount.name }}
      serviceAccountName: {{ .Values.cloudserviceaccount.name }}
      {{- else }}
      serviceAccount: ""
      serviceAccountName: ""
      {{- end }}
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}

      imagePullSecrets:
      - name: {{ .Values.dockerconfigjson.name }}

      volumes:
      {{- range $v := .Values.configMaps }}
      - configMap:
          name: {{ $v.name }}
          optional: false
        name: {{ $v.name }}
      {{- end }}
      {{- range $v := .Values.config.sharedNamespaceConfigMaps }}
      - configMap:
          name: {{ $v.name }}
          optional: false
        name: {{ $v.name }}
      {{- end }}
      {{- if and (.Values.persistentVolume.enabled) (eq .Values.deployment.kind "Deployment") }}
      - name: storage-volume
        persistentVolumeClaim:
          claimName: {{ include "app.fullname" . }}
      {{- end }}

      {{- if .Values.affinity }}
      affinity:
      {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
      - name: "{{ include "app.fullname" . }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}

        {{- if .Values.config.command }}
        command:
        {{- range $v := .Values.config.command }}
        - "{{ $v }}"
        {{- end }}
        {{- end }}

        {{- if .Values.config.args }}
        args:
        {{- range $v := .Values.config.args }}
        - "{{ $v }}"
        {{- end }}
        {{- end }}

        {{- if .Values.config.env }}
        env:
        {{- range $k, $v := .Values.config.env }}
        - name: "{{ $k }}"
          value: "{{ $v }}"
        {{- end }}
        {{- end }}
        
        {{- if or .Values.config.secrets .Values.config.secretsB64 }}
        envFrom:
        - secretRef:
            name: {{ include "app.secret.fullname" . }}
        {{- end }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        {{- if or (ne .Values.readinessProbe.httpGet.path "") (.Values.readinessProbe.exec.command) }}
        readinessProbe:
          {{- if ne .Values.readinessProbe.httpGet.path "" }}
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.service.port }}
            scheme: HTTP
          {{- end }}
          {{- if gt (len .Values.readinessProbe.exec.command) 0 }}
          exec:
            command:
          {{- range $v := .Values.readinessProbe.exec.command }}
            - {{ $v }}
          {{- end }}
          {{- end }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
        {{- end }}

        {{- if or (ne .Values.livenessProbe.httpGet.path "") (.Values.livenessProbe.exec.command) }}
        livenessProbe:
          {{- if ne .Values.livenessProbe.httpGet.path "" }}
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port }}
            scheme: HTTP
          {{- end }}
          {{- if gt (len .Values.livenessProbe.exec.command) 0 }}
          exec:
            command:
          {{- range $v := .Values.livenessProbe.exec.command }}
            - {{ $v }}
          {{- end }}
          {{- end }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
        {{- end }}

        volumeMounts:
        {{- range $v := .Values.configMaps }}
        - mountPath: "{{ $v.mountPath }}"
          {{- if $v.mountPropagation }}
          mountPropagation: {{ $v.mountPropagation }}
          {{- else }}
          mountPropagation: None
          {{- end }}
          name: {{ $v.name }}
        {{- end }}
        {{- range $v := .Values.config.sharedNamespaceConfigMaps }}
        - name: "{{ $v.name }}"
          mountPath: "{{ $v.mountPath }}"
          mountPropagation: {{ default "None" $v.mountPropagation }}
          readOnly: {{ default true $v.readOnly }}
        {{- end }}
        {{- if and (.Values.persistentVolume.enabled) (eq .Values.deployment.kind "Deployment") }}
        - name: storage-volume
          mountPath: {{ .Values.persistentVolume.mountPath }}
          subPath: "{{ .Values.persistentVolume.subPath }}"
        {{- end }}
        {{- if and (.Values.persistentVolume.enabled) (eq .Values.deployment.kind "StatefulSet") }}
        - name: {{ include "app.fullname" . }}
          mountPath: {{ .Values.persistentVolume.mountPath }}
          subPath: "{{ .Values.persistentVolume.subPath }}"
        {{- end }}
  {{- if and (.Values.persistentVolume.enabled) (eq .Values.deployment.kind "StatefulSet") }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.persistentVolume.statefulSetRetentionPolicy.whenDeleted }}
    whenScaled: {{ .Values.persistentVolume.statefulSetRetentionPolicy.whenScaled }}
  volumeClaimTemplates:
  - metadata:
      annotations:
        {{- with .Values.persistentVolume.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- with .Values.persistentVolume.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      name: {{ include "app.fullname" . }}
    spec:
      accessModes:
{{ toYaml .Values.persistentVolume.accessModes | indent 6 }}
    {{- if .Values.persistentVolume.storageClass }}
    {{- if (eq "-" .Values.persistentVolume.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistentVolume.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.persistentVolume.size }}"
  {{- end }}
