{{- range .Values.service.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required "A valid hostname is required!" .hostname }}
  annotations:
  {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
  {{- end}}
  {{- if .enableTraefik | default "true" }}
    traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
  {{- end}}
  {{- if $.Values.service.ingressIPAllowlist }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace}}-{{ include "app.fullname" $ }}-ipallowlist@kubernetescrd
  {{- end }}
spec:
  {{- if .enableTraefik | default "true" }}
  ingressClassName: traefik
  {{- end}}
  tls:
  - hosts:
      - "{{ .hostname }}"
    secretName: {{ .hostname }}-tls
  rules:
    - host: "{{ required "A valid hostname is required!" .hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ include "app.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
