{{- if .Values.global.deployTraefikIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.service.traefik.entrypoint }}

spec:
  rules:
    - host: {{ .Values.service.traefik.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ include "app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
