{{- if or .Values.config.secrets .Values.config.secretsB64 }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "app.secret.fullname" . }}
  labels:
    {{ include "snowplow.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.config.secrets }}
  {{ $k }}: "{{ $v | b64enc }}"
  {{- end }}
  {{- range $k, $v := .Values.config.secretsB64 }}
  {{ $k }}: "{{ $v }}"
  {{- end }}
{{- end }}
