{{- if .Values.service.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
  {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end}}
  {{- if and (eq .Values.global.cloud "gcp") (ne .Values.service.gcp.networkEndpointGroupName "") }}
    cloud.google.com/app-protocols:  '{"http-port": "HTTP"}'
    cloud.google.com/neg: '{"exposed_ports": {"{{ .Values.service.port }}":{"name": "{{ include "service.gcp.networkEndpointGroupName" . }}"}}}'
  {{- end }}
spec:
  type: NodePort
  selector:
    app: {{ include "app.fullname" . }}
  ports:
  - name: http-port
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
{{- end }}
