{{- if .Values.service.deploy }}
{{- if and (eq .Values.global.cloud "aws")  (ne .Values.service.aws.targetGroupARN "") }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{ include "snowplow.labels" $ | nindent 4 }}
spec:
  serviceRef:
    name: {{ include "app.fullname" . }}
    port: {{ .Values.service.port }}
  targetGroupARN: {{ .Values.service.aws.targetGroupARN }}
{{- end }}
{{- end }}
