{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "snowplow.labels" $ | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: {{ .Values.deployment.kind }}
    name: {{ include "app.fullname" . }}
  {{- if .Values.vpa.spec }}
  {{- toYaml .Values.vpa.spec | nindent 2 }}
  {{- end }}
{{- end }}