apiVersion: v2
name: github-actions-runners
description: A helm chart for deploying Github Self-hosted Runners
type: application
version: 0.1.1
icon: https://raw.githubusercontent.com/snowplow-devops/helm-charts/master/docs/logo/snowplow.png
home: https://github.com/snowplow-devops/helm-charts
sources:
  - https://github.com/snowplow-devops/helm-charts
maintainers:
  - name: gthomson31
    url: https://github.com/gthomson31
    email: gthomson31@users.noreply.github.com
keywords:
  - github-actions
  - actions-runner-controller
dependencies:
  - name: dockerconfigjson
    version: 0.1.0
    repository: "https://snowplow-devops.github.io/helm-charts"
    condition: image.isRepositoryPrivate
