runnerDeployment:
  enabled: true
  isRepositoryPublic: true
  runnerDeploymentName: "github-runner-deployment"
  deploymentType: "repository"
  repositoryName: "FOR USE WITH REPO DEPLOYMENT TYPE"
  organizationName: "FOR USE WITH  Organization DEPLOYMENT TYPE"
  enterpriseName: "FOR USE WITH Enterprise DEPLOYMENT TYPE"
  runnerNamespace: "github-runners"
  
  image:
    runnerImage: "summerwind/actions-runner"
    tag: "latest"
    pullPolicy: IfNotPresent
  minimumReplicaCount: "1"
  maximumReplicaCount: "1"

secrets:
  docker:
    name: "dockerhub"
    username: ""
    password: ""
    server: "https://index.docker.io/v1/"
    email: ""


