apiVersion: v2
name: aws-target-group-binding
description: A Helm chart for deploying a TargetGroupBinding for use with the AWS LoadBalancer Controller
type: application
version: 0.1.0
icon: https://raw.githubusercontent.com/snowplow-devops/helm-charts/master/docs/logo/snowplow.png
home: https://github.com/snowplow-devops/helm-charts
sources:
  - https://github.com/snowplow-devops/helm-charts
maintainers:
  - name: gthomson31
    url: https://github.com/gthomson31
    email: gthomson31@users.noreply.github.com
keywords:
  - kubernetes
  - loadbalancer
  - aws
