apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
type: kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{ tpl (.Files.Get "configs/secret.json") . | b64enc }}
