apiVersion: v1
name: aws-load-balancer-controller-crds
description: AWS Load Balancer Controller CRDs Helm chart for Kubernetes
version: 0.2.0
appVersion: "v3.4.2"
home: https://github.com/snowplow-devops/helm-charts
icon: https://raw.githubusercontent.com/snowplow-devops/helm-charts/master/docs/logo/snowplow.png
sources:
  - https://github.com/snowplow-devops/helm-charts
  - https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/crds/crds.yaml
  - https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/crds/gateway-crds.yaml
maintainers:
  - name: jbeemster
    url: https://github.com/jbeemster
    email: jbeemster@users.noreply.github.com
keywords:
  - eks
  - alb
  - load balancer
  - ingress
  - nlb
