{{- if .Values.service.gcp.deployProxy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iglu.cloudsqlproxy.name" . }}
  labels:
    {{ include "snowplow.labels" $ | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ include "iglu.cloudsqlproxy.name" . }}
  ports:
  - port: {{ .Values.service.gcp.proxy.port }}
    protocol: TCP
    targetPort: {{ .Values.service.config.database.port }}
{{- end }}
