{{- if and .Values.service.ingressIPAllowlist .Values.service.ingress -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "iglu.app.name" . }}-ipallowlist
  labels:
    {{ include "snowplow.labels" $ | nindent 4 }}
spec:
  ipWhiteList:
    sourceRange:
      {{- range $ip := .Values.service.ingressIPAllowlist }}
      - "{{ $ip }}"
      {{- end }}
{{- end -}}
