{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "iglu.app.secret.name" . }}
type: Opaque
data:
  CONFIG_FORCE_iglu_superApiKey: "{{ include "iglu.service.config.superApiKey" . | b64enc }}"
  CONFIG_FORCE_iglu_database_password: "{{ .Values.service.config.database.secrets.password | b64enc }}"
  CONFIG_FORCE_iglu_database_username: "{{ .Values.service.config.database.secrets.username | b64enc }}"
{{- end }}