{{- range .Values.service.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "iglu.app.name" $ }}
  {{- if $.Values.service.ingress.enableTraefik | default "true" }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
  {{- end}}
spec:
  {{- if $.Values.service.ingress.enableTraefik | default "true" }}
  ingressClassName: traefik
  {{- end}}
  tls:
  - hosts:
      - "{{ .hostname }}"
    secretName: {{ .hostname }}-tls
  rules:
    - host: "{{ required "A valid hostname is required!" .hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ include "iglu.app.name" $ }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
