# -- Overrides the name given to the deployment (default: .Release.Name)
nameOverride: ""
# -- Overrides the full-name given to the deployment resources (default: .Release.Name)
fullnameOverride: ""

image:
  # -- Image to use for deploying
  repository: public.ecr.aws/aws-observability/aws-otel-collector
  tag: v0.33.1
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

serviceAccount:
  # -- Whether to create a service account or not
  create: true
  # -- The name of the service account to create or use
  name: ""
  # -- Optional annotations to be applied to service account
  annotations: {}

# -- Determines whether to enable kube state metrics collection with Prometheus
kube_state_metrics_enabled: false

# -- Set the retention for log group /aws/containerinsights/{ClusterName}/performance
performance_log_retention_in_days: 30

# -- Set the retention for log group /aws/containerinsights/{TaskId}/prometheus
prometheus_log_retention_in_days: 30

# -- Set tags to log groups created by otel collector awsemfexporter
tags: {}
