{{- if .Values.clusterrole.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.fullname" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "app.fullname" . }}-role
subjects:
{{- if .Values.cloudserviceaccount.deploy }}
- apiGroup:
  kind: ServiceAccount
  name: {{ .Values.cloudserviceaccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- end }}
