{{- if .Values.clusterrole.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{ include "snowplow.labels" $ | nindent 4 }}
rules:
{{- toYaml $.Values.clusterrole.rules  | nindent 2 }}
---
{{- end }}
