{{- if .Values.service.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
  {{- range $k, $v := .Values.service.labels }}
    {{ $k }}: {{ $v }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "app.fullname" . }}
  ports:
  - name: {{ .Values.service.name }}-port
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
{{- end }}
