{{- if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  annotations:
  {{- if and (eq .Values.global.cloud "gcp") (.Values.gcp.serviceAccount) }}
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccount }}
  {{- else if and (eq .Values.global.cloud "aws") (.Values.aws.roleARN) }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleARN }}
  {{- else if and (eq .Values.global.cloud "azure") (.Values.azure.managedIdentityId) }}
    azure.workload.identity/client-id: {{ .Values.azure.managedIdentityId }}
  {{- end }}
{{- if .Values.secrets }}
secrets:
{{- range $v := .Values.secrets }}
-  name: {{ $v }}
{{- end }}
{{- end }}
{{- end }}
