{{- if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  annotations:
  {{- if eq .Values.global.cloud "gcp" }}
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccount }}
  {{- else if eq .Values.global.cloud "aws" }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleARN }}
  {{- end }}
{{- end }}
