apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-thrift-server.fullname" . }}
  labels:
    {{- include "spark-thrift-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: thrift
      protocol: TCP
      name: thrift
  selector:
    {{- include "spark-thrift-server.selectorLabels" . | nindent 4 }}
